package commandboundary

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const shimMarker = "# Boundary project-local command shim."

var defaultShimCommands = []string{
	"git",
	"gh",
	"rm",
	"mv",
	"cp",
	"curl",
	"wget",
	"npm",
	"pnpm",
	"yarn",
	"bun",
	"node",
	"python",
	"python3",
	"docker",
	"kubectl",
	"terraform",
	"psql",
}

type ShimResult struct {
	ProjectRoot string
	BinDir      string
	Commands    []string
	Created     []string
	Removed     []string
	Skipped     []string
}

func DefaultShimCommands() []string {
	return append([]string(nil), defaultShimCommands...)
}

func ProjectBinDir(projectRoot string) string {
	return filepath.Join(projectRoot, ".boundary", "bin")
}

func InstallProjectShims(projectRoot string, commands []string) (ShimResult, error) {
	root, err := cleanProjectRoot(projectRoot)
	if err != nil {
		return ShimResult{}, err
	}
	commands, err = normalizeShimCommands(commands)
	if err != nil {
		return ShimResult{}, err
	}
	binDir := ProjectBinDir(root)
	if err := os.MkdirAll(binDir, 0o755); err != nil { // #nosec G301 -- project-local shim directories must be traversable by the user's shell.
		return ShimResult{}, err
	}

	result := ShimResult{
		ProjectRoot: root,
		BinDir:      binDir,
		Commands:    commands,
	}
	for _, command := range commands {
		path := filepath.Join(binDir, command)
		if err := os.WriteFile(path, []byte(ShimScript(command)), 0o755); err != nil { // #nosec G306 -- command shims must be executable.
			return ShimResult{}, err
		}
		result.Created = append(result.Created, path)
	}
	return result, nil
}

func UninstallProjectShims(projectRoot string, commands []string) (ShimResult, error) {
	root, err := cleanProjectRoot(projectRoot)
	if err != nil {
		return ShimResult{}, err
	}
	commands, err = normalizeShimCommands(commands)
	if err != nil {
		return ShimResult{}, err
	}
	binDir := ProjectBinDir(root)
	result := ShimResult{
		ProjectRoot: root,
		BinDir:      binDir,
		Commands:    commands,
	}
	for _, command := range commands {
		path := filepath.Join(binDir, command)
		body, err := os.ReadFile(path) // #nosec G304 -- command names are validated before joining under the project-local shim directory.
		if errors.Is(err, os.ErrNotExist) {
			result.Skipped = append(result.Skipped, path)
			continue
		}
		if err != nil {
			return ShimResult{}, err
		}
		if !strings.Contains(string(body), shimMarker) {
			result.Skipped = append(result.Skipped, path)
			continue
		}
		if err := os.Remove(path); err != nil {
			return ShimResult{}, err
		}
		result.Removed = append(result.Removed, path)
	}
	return result, nil
}

func ShimScript(command string) string {
	return fmt.Sprintf(`#!/usr/bin/env sh
%s
# Generated by boundary command install --project.
exec boundary command run -- %s "$@"
`, shimMarker, command)
}

func cleanProjectRoot(projectRoot string) (string, error) {
	if strings.TrimSpace(projectRoot) == "" {
		return "", errors.New("project root is required")
	}
	return filepath.Abs(projectRoot)
}

func normalizeShimCommands(commands []string) ([]string, error) {
	if len(commands) == 0 {
		commands = DefaultShimCommands()
	}
	seen := map[string]bool{}
	out := make([]string, 0, len(commands))
	for _, command := range commands {
		command = strings.TrimSpace(command)
		if err := validateShimCommand(command); err != nil {
			return nil, err
		}
		if seen[command] {
			continue
		}
		seen[command] = true
		out = append(out, command)
	}
	return out, nil
}

func validateShimCommand(command string) error {
	if command == "" {
		return errors.New("shim command cannot be empty")
	}
	if strings.ContainsAny(command, `/\`) || strings.ContainsAny(command, " \t\r\n") {
		return fmt.Errorf("invalid shim command %q", command)
	}
	return nil
}
