// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: adapters/grpc/stream.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StreamSvcClient is the client API for StreamSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamSvcClient interface {
	ClientStream(ctx context.Context, opts ...grpc.CallOption) (StreamSvc_ClientStreamClient, error)
	ServerStream(ctx context.Context, in *Msg, opts ...grpc.CallOption) (StreamSvc_ServerStreamClient, error)
	BidiStream(ctx context.Context, opts ...grpc.CallOption) (StreamSvc_BidiStreamClient, error)
}

type streamSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamSvcClient(cc grpc.ClientConnInterface) StreamSvcClient {
	return &streamSvcClient{cc}
}

func (c *streamSvcClient) ClientStream(ctx context.Context, opts ...grpc.CallOption) (StreamSvc_ClientStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamSvc_ServiceDesc.Streams[0], "/grpc.StreamSvc/ClientStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamSvcClientStreamClient{stream}
	return x, nil
}

type StreamSvc_ClientStreamClient interface {
	Send(*Msg) error
	CloseAndRecv() (*Msg, error)
	grpc.ClientStream
}

type streamSvcClientStreamClient struct {
	grpc.ClientStream
}

func (x *streamSvcClientStreamClient) Send(m *Msg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamSvcClientStreamClient) CloseAndRecv() (*Msg, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Msg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamSvcClient) ServerStream(ctx context.Context, in *Msg, opts ...grpc.CallOption) (StreamSvc_ServerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamSvc_ServiceDesc.Streams[1], "/grpc.StreamSvc/ServerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamSvcServerStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StreamSvc_ServerStreamClient interface {
	Recv() (*Msg, error)
	grpc.ClientStream
}

type streamSvcServerStreamClient struct {
	grpc.ClientStream
}

func (x *streamSvcServerStreamClient) Recv() (*Msg, error) {
	m := new(Msg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamSvcClient) BidiStream(ctx context.Context, opts ...grpc.CallOption) (StreamSvc_BidiStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &StreamSvc_ServiceDesc.Streams[2], "/grpc.StreamSvc/BidiStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamSvcBidiStreamClient{stream}
	return x, nil
}

type StreamSvc_BidiStreamClient interface {
	Send(*Msg) error
	Recv() (*Msg, error)
	grpc.ClientStream
}

type streamSvcBidiStreamClient struct {
	grpc.ClientStream
}

func (x *streamSvcBidiStreamClient) Send(m *Msg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamSvcBidiStreamClient) Recv() (*Msg, error) {
	m := new(Msg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamSvcServer is the server API for StreamSvc service.
// All implementations must embed UnimplementedStreamSvcServer
// for forward compatibility
type StreamSvcServer interface {
	ClientStream(StreamSvc_ClientStreamServer) error
	ServerStream(*Msg, StreamSvc_ServerStreamServer) error
	BidiStream(StreamSvc_BidiStreamServer) error
	mustEmbedUnimplementedStreamSvcServer()
}

// UnimplementedStreamSvcServer must be embedded to have forward compatible implementations.
type UnimplementedStreamSvcServer struct {
}

func (UnimplementedStreamSvcServer) ClientStream(StreamSvc_ClientStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStream not implemented")
}
func (UnimplementedStreamSvcServer) ServerStream(*Msg, StreamSvc_ServerStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerStream not implemented")
}
func (UnimplementedStreamSvcServer) BidiStream(StreamSvc_BidiStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method BidiStream not implemented")
}
func (UnimplementedStreamSvcServer) mustEmbedUnimplementedStreamSvcServer() {}

// UnsafeStreamSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamSvcServer will
// result in compilation errors.
type UnsafeStreamSvcServer interface {
	mustEmbedUnimplementedStreamSvcServer()
}

func RegisterStreamSvcServer(s grpc.ServiceRegistrar, srv StreamSvcServer) {
	s.RegisterService(&StreamSvc_ServiceDesc, srv)
}

func _StreamSvc_ClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamSvcServer).ClientStream(&streamSvcClientStreamServer{stream})
}

type StreamSvc_ClientStreamServer interface {
	SendAndClose(*Msg) error
	Recv() (*Msg, error)
	grpc.ServerStream
}

type streamSvcClientStreamServer struct {
	grpc.ServerStream
}

func (x *streamSvcClientStreamServer) SendAndClose(m *Msg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamSvcClientStreamServer) Recv() (*Msg, error) {
	m := new(Msg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StreamSvc_ServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Msg)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamSvcServer).ServerStream(m, &streamSvcServerStreamServer{stream})
}

type StreamSvc_ServerStreamServer interface {
	Send(*Msg) error
	grpc.ServerStream
}

type streamSvcServerStreamServer struct {
	grpc.ServerStream
}

func (x *streamSvcServerStreamServer) Send(m *Msg) error {
	return x.ServerStream.SendMsg(m)
}

func _StreamSvc_BidiStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamSvcServer).BidiStream(&streamSvcBidiStreamServer{stream})
}

type StreamSvc_BidiStreamServer interface {
	Send(*Msg) error
	Recv() (*Msg, error)
	grpc.ServerStream
}

type streamSvcBidiStreamServer struct {
	grpc.ServerStream
}

func (x *streamSvcBidiStreamServer) Send(m *Msg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamSvcBidiStreamServer) Recv() (*Msg, error) {
	m := new(Msg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamSvc_ServiceDesc is the grpc.ServiceDesc for StreamSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.StreamSvc",
	HandlerType: (*StreamSvcServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClientStream",
			Handler:       _StreamSvc_ClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ServerStream",
			Handler:       _StreamSvc_ServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BidiStream",
			Handler:       _StreamSvc_BidiStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "adapters/grpc/stream.proto",
}
